# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://cluelessog.github.io/"
theme = "congo"
defaultContentLanguage = "en"
languageCode = "en"
enableRobotsTXT = true
paginate = 10
summaryLength = 0
disableLiveReload = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
[permalinks]
  blog = '/:year/:month/:title/'