

title = "Clueless Says"
# logo = "img/logo.jpg"
# description = "Playing the online game"
copyright = "Copy, _right?_ :thinking_face: Yes I Own Everything Here"



[params.author]
   name = "Sourabh Kumar"
   image = "img/profile.png"
   headline = "Playing The Great Online Game"
  #  bio = "A little bit about you"
   links = [
    #  { email = "mailto:hello@your_domain.com" },
    #  { link = "https://link-to-some-website.com/" },
    #  { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    #  { apple = "https://www.apple.com" },
    #  { blogger = "https://username.blogspot.com/" },
    #  { codepen = "https://codepen.io/username" },
    #  { dev = "https://dev.to/username" },
    #  { discord = "https://discord.gg/invitecode" },
    #  { dribbble = "https://dribbble.com/username" },
     { facebook = "https://facebook.com/cluelessog" },
    #  { flickr = "https://www.flickr.com/photos/username/" },
    #  { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/cluelessog" },
    #  { gitlab = "https://gitlab.com/username" },
    #  { google = "https://www.google.com/" },
     { instagram = "https://instagram.com/cluelessog" },
    #  { keybase = "https://keybase.io/username" },
    #  { kickstarter = "https://www.kickstarter.com/profile/username" },
    #  { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://linkedin.com/in/cluelessog" },
    #  { mastodon = "https://mastodon.instance/@username" },
    #  { medium = "https://medium.com/username" },
    #  { microsoft = "https://www.microsoft.com/" },
    #  { patreon = "https://www.patreon.com/username" },
    #  { pinterest = "https://pinterest.com/username" },
     { reddit = "https://reddit.com/user/clueless_og" },
    #  { slack = "https://workspace.url/team/userid" },
    #  { snapchat = "https://snapchat.com/add/username" },
    #  { soundcloud = "https://soundcloud.com/username" },
     { steam = "https://steamcommunity.com/id/cluelessog" },
    #  { telegram = "https://t.me/username" },
    #  { tiktok = "https://tiktok.com/@username" },
    #  { tumblr = "https://username.tumblr.com" },
     { twitch = "https://twitch.tv/clueless_og" },
     { twitter = "https://twitter.com/cluelesssOg" },
    #  { whatsapp = "https://wa.me/phone-number" },
    #  { youtube = "https://www.youtube.com/channel/UC8ajFP6whuAbEUaA0SuxyfA" },
   ]
languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false
dateFormat = "2 January 2006"